# Generated by Django 4.2.3 on 2023-07-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comercio', models.CharField(max_length=30, verbose_name='Comercio')),
                ('titular', models.CharField(max_length=30, verbose_name='Titular de Comercio')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre y Apellido')),
                ('legajo', models.IntegerField(verbose_name='Legajo N°')),
                ('dni', models.IntegerField(verbose_name='DNI')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_empleado', models.IntegerField()),
                ('id_comercio', models.IntegerField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Compra')),
                ('cuotas', models.IntegerField(verbose_name='Cuotas')),
                ('fecha', models.DateTimeField(verbose_name='Fecha de Compra')),
            ],
        ),
    ]
