# Generated by Django 4.2.3 on 2023-07-27 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comercio',
            options={'ordering': ['comercio'], 'verbose_name': 'Comercio', 'verbose_name_plural': 'Comercios'},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['nombre'], 'verbose_name': 'empleado', 'verbose_name_plural': 'empleados'},
        ),
        migrations.AlterField(
            model_name='orden',
            name='id_comercio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.comercio'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='id_empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.empleado'),
        ),
        migrations.AlterModelTable(
            name='comercio',
            table='comercio',
        ),
        migrations.AlterModelTable(
            name='empleado',
            table='empleado',
        ),
    ]
