# Generated by Django 4.2.3 on 2023-07-27 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_alter_comercio_options_alter_empleado_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='id_comercio',
            new_name='comercio',
        ),
        migrations.RenameField(
            model_name='orden',
            old_name='id_empleado',
            new_name='empleado',
        ),
    ]
