# Generated by Django 4.2.3 on 2023-07-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_rename_id_comercio_orden_comercio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='fecha',
            field=models.DateField(verbose_name='Fecha de Compra'),
        ),
        migrations.AlterModelTable(
            name='orden',
            table='ordenes_orden',
        ),
    ]
