# Generated by Django 4.2.3 on 2023-09-03 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0006_alter_margen_options_alter_orden_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='valorcuota',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor de Cuota'),
        ),
    ]
