# Generated by Django 4.2.3 on 2023-09-03 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0009_alter_empleado_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercio',
            name='activo',
            field=models.BooleanField(default=True, null=True, verbose_name='Activo'),
        ),
    ]
